name: CI/CD - Build & Deploy to EKS (Manual)

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-1
  ACCOUNT_ID: 615299736509
  ECR_REPOSITORY: demo-app
  CLUSTER_NAME: eks-prod-cluster
  DEPLOYMENT_NAME: demo-app
  CONTAINER_NAME: demo-app

jobs:
  deploy:
    name: Build & Deploy to EKS
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configure AWS credentials using OIDC
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::615299736509:role/GitHubActionsEKSRole
          aws-region: eu-west-1

      # 3️⃣ Login to Amazon ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # 4️⃣ Build & Push Docker Image
      - name: Build & Push Docker Image
        run: |
          IMAGE_TAG=${{ github.sha }}

          docker build -t demo-app:$IMAGE_TAG ./app

          docker tag demo-app:$IMAGE_TAG \
            615299736509.dkr.ecr.eu-west-1.amazonaws.com/demo-app:$IMAGE_TAG

          docker push \
            615299736509.dkr.ecr.eu-west-1.amazonaws.com/demo-app:$IMAGE_TAG

      # 5️⃣ Update kubeconfig
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region eu-west-1 \
            --name eks-prod-cluster

      # 6️⃣ Deploy to EKS
      - name: Deploy to EKS
        run: |
          kubectl set image deployment/demo-app \
            demo-app=615299736509.dkr.ecr.eu-west-1.amazonaws.com/demo-app:${{ github.sha }}
